apiVersion: v1
kind: Service
metadata:
  name: tps-react-app
  namespace: tps
  labels:
    tps: react-app
  annotations:
    tps-app-type: front-end
spec:
  selector:
    app: tps-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31063
  type: NodePort
  